# ==============================================================================
# Merged Lakeflow Source: uipathqueues
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from datetime import datetime, timedelta
from decimal import Decimal
from typing import Any, Iterator
import io
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *
import base64
import csv
import requests
import zipfile


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str):
            if not value.strip():
                raise ValueError(f"Cannot convert empty string to integer")
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        if isinstance(value, str) and not value.strip():
            raise ValueError(f"Cannot convert empty string to float")
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        if isinstance(value, str):
            if not value.strip():
                raise ValueError(f"Cannot convert empty string to Decimal")
            return Decimal(value)
        return Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            if not value.strip():
                raise ValueError(f"Cannot convert empty string to boolean")
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            if not value.strip():
                raise ValueError(f"Cannot convert empty string to date")
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            if not value.strip():
                raise ValueError(f"Cannot convert empty string to timestamp")
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Treat empty strings as None for all types except StringType
        if isinstance(value, str) and not value.strip() and not isinstance(field_type, StringType):
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # sources/uipathqueues/uipathqueues.py
    ########################################################

    class LakeflowConnect:
        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the UiPath Orchestrator connector with connection-level options.

            Expected options:
                - organization_name: UiPath organization name
                - tenant_name: UiPath tenant name
                - client_id: OAuth App ID for client credentials flow
                - client_secret: OAuth App Secret for client credentials flow
                - folder_id: Organization unit ID (folder) to query
                - scope (optional): OAuth scopes (defaults to "OR.Queues OR.Execution")
            """
            self.organization_name = options.get("organization_name")
            self.tenant_name = options.get("tenant_name")
            self.client_id = options.get("client_id")
            self.client_secret = options.get("client_secret")
            self.folder_id = options.get("folder_id")
            self.scope = options.get("scope", "OR.Queues OR.Execution")

            if not self.organization_name:
                raise ValueError("UiPath connector requires 'organization_name' in options")
            if not self.tenant_name:
                raise ValueError("UiPath connector requires 'tenant_name' in options")
            if not self.client_id:
                raise ValueError("UiPath connector requires 'client_id' in options")
            if not self.client_secret:
                raise ValueError("UiPath connector requires 'client_secret' in options")
            if not self.folder_id:
                raise ValueError("UiPath connector requires 'folder_id' in options")

            self.identity_base_url = f"https://cloud.uipath.com/{self.organization_name}/identity_"
            self.api_base_url = f"https://cloud.uipath.com/{self.organization_name}/{self.tenant_name}/orchestrator_"

            # Access token will be obtained and cached
            self._access_token = None
            self._token_expires_at = None

            # Configure session
            self._session = requests.Session()

        def _get_access_token(self) -> str:
            """
            Obtain or refresh access token using OAuth client credentials flow.
            Tokens are cached and refreshed when expired.
            """
            # Return cached token if still valid
            if self._access_token and self._token_expires_at:
                if datetime.now() < self._token_expires_at:
                    return self._access_token

            # Obtain new access token
            token_url = f"{self.identity_base_url}/connect/token"

            payload = {
                "grant_type": "client_credentials",
                "client_id": self.client_id,
                "client_secret": self.client_secret,
                "scope": self.scope,
            }

            response = requests.post(
                token_url,
                data=payload,
                headers={"Content-Type": "application/x-www-form-urlencoded"},
            )

            if response.status_code != 200:
                raise RuntimeError(
                    f"Failed to obtain access token: {response.status_code} {response.text}"
                )

            token_data = response.json()
            self._access_token = token_data["access_token"]
            expires_in = token_data.get("expires_in", 3600)

            # Set expiration time with a 5-minute buffer
            self._token_expires_at = datetime.now() + timedelta(seconds=expires_in - 300)

            return self._access_token

        def _get_headers(self) -> dict:
            """
            Get HTTP headers with access token and folder ID.
            """
            return {
                "Authorization": f"Bearer {self._get_access_token()}",
                "X-UIPATH-OrganizationUnitId": self.folder_id,
                "Accept": "application/json",
            }

        def list_tables(self) -> list[str]:
            """
            List names of all tables supported by this connector.
            """
            return ["queue_items"]

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            """
            if table_name not in self.list_tables():
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {self.list_tables()}"
                )

            if table_name == "queue_items":
                # Nested Robot struct
                robot_struct = StructType(
                    [
                        StructField("Id", LongType(), True),
                        StructField("Name", StringType(), True),
                        StructField("Type", StringType(), True),
                    ]
                )

                # Nested ReviewerUser struct
                reviewer_user_struct = StructType(
                    [
                        StructField("Id", LongType(), True),
                        StructField("Username", StringType(), True),
                        StructField("Email", StringType(), True),
                    ]
                )

                # Main queue_items schema
                schema = StructType(
                    [
                        StructField("Id", LongType(), False),
                        StructField("QueueDefinitionId", LongType(), True),
                        StructField("Name", StringType(), True),
                        StructField("Priority", StringType(), True),
                        StructField("Status", StringType(), True),
                        StructField("ReviewStatus", StringType(), True),
                        StructField("Reference", StringType(), True),
                        StructField("ProcessingException", StringType(), True),
                        StructField("DueDate", TimestampType(), True),
                        StructField("RiskSlaDate", TimestampType(), True),
                        StructField("DeferDate", TimestampType(), True),
                        StructField("StartProcessing", TimestampType(), True),
                        StructField("EndProcessing", TimestampType(), True),
                        StructField("SecondsInPreviousAttempts", IntegerType(), True),
                        StructField("AncestorId", LongType(), True),
                        StructField("RetryNumber", IntegerType(), True),
                        StructField("SpecificContent", StringType(), True),  # JSON string
                        StructField("Output", StringType(), True),  # JSON string
                        StructField("Progress", StringType(), True),
                        StructField("CreationTime", TimestampType(), True),
                        StructField("LastModificationTime", TimestampType(), True),
                        StructField("Robot", robot_struct, True),
                        StructField("ReviewerUser", reviewer_user_struct, True),
                        StructField("OrganizationUnitId", LongType(), True),
                    ]
                )
                return schema

            raise ValueError(f"Unknown table: {table_name}")

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            """
            if table_name not in self.list_tables():
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {self.list_tables()}"
                )

            if table_name == "queue_items":
                return {
                    "primary_keys": ["Id"],
                    "cursor_field": "LastModificationTime",
                    "ingestion_type": "append",
                }

            raise ValueError(f"Unknown table: {table_name}")

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read data from a table and return an iterator of records along with the next offset.

            For queue_items, table_options can include:
                - queue_definition_id (required): ID of the queue to export items from
                - filter (optional): OData filter expression
                - expand (optional): Related entities to expand (default: "Robot,ReviewerUser")
            """
            if table_name not in self.list_tables():
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {self.list_tables()}"
                )

            if table_name == "queue_items":
                queue_definition_id = table_options.get("queue_definition_id")
                if not queue_definition_id:
                    raise ValueError(
                        "table_options must include 'queue_definition_id' for queue_items table"
                    )

                # Build filter for incremental reads
                filter_expr = table_options.get("filter", "")
                if start_offset and "last_modification_time" in start_offset:
                    last_mod_time = start_offset["last_modification_time"]
                    time_filter = f"(LastModificationTime ge {last_mod_time})"
                    if filter_expr:
                        filter_expr = f"({filter_expr}) and {time_filter}"
                    else:
                        filter_expr = time_filter

                expand = table_options.get("expand", "Robot,ReviewerUser")

                # Execute 3-step export process
                records_iterator = self._export_queue_items(
                    queue_definition_id, filter_expr, expand
                )

                # Track the maximum LastModificationTime for the next offset
                max_modification_time = start_offset.get("last_modification_time", "")

                # Wrap iterator to track max timestamp
                def tracked_iterator():
                    nonlocal max_modification_time
                    for record in records_iterator:
                        last_mod = record.get("LastModificationTime")
                        if last_mod and last_mod > max_modification_time:
                            max_modification_time = last_mod
                        yield record

                return tracked_iterator(), {
                    "last_modification_time": max_modification_time
                }

            raise ValueError(f"Unknown table: {table_name}")

        def _export_queue_items(
            self, queue_definition_id: str, filter_expr: str, expand: str
        ) -> Iterator[dict]:
            """
            Execute the 3-step export process for queue items:
            1. Initiate export
            2. Poll export status
            3. Download CSV and parse records
            """
            # Step 1: Initiate export
            export_id = self._initiate_export(queue_definition_id, filter_expr, expand)

            # Step 2: Poll export status until completed
            self._poll_export_status(export_id)

            # Step 3: Get download link and download CSV
            download_url = self._get_download_link(export_id)

            # Download and parse CSV
            csv_content = self._download_csv(download_url)

            # Parse CSV and yield records
            yield from self._parse_csv(csv_content)

        def _initiate_export(
            self, queue_definition_id: str, filter_expr: str, expand: str
        ) -> int:
            """
            Step 1: Initiate export and return export ID.
            """
            url = f"{self.api_base_url}/odata/QueueDefinitions({queue_definition_id})/UiPathODataSvc.Export"

            # Build query parameters
            params = []
            if filter_expr:
                params.append(f"$filter={filter_expr}")
            if expand:
                params.append(f"$expand={expand}")

            if params:
                url += "?" + "&".join(params)

            headers = self._get_headers()
            headers["Content-Length"] = "0"

            response = requests.post(url, headers=headers)

            if response.status_code != 200:
                raise RuntimeError(
                    f"Failed to initiate export: {response.status_code} {response.text}"
                )

            export_data = response.json()
            export_id = export_data.get("Id")

            if not export_id:
                raise RuntimeError(f"Export response missing 'Id': {export_data}")

            return export_id

        def _poll_export_status(
            self, export_id: int, max_wait_seconds: int = 600, poll_interval: int = 5
        ) -> None:
            """
            Step 2: Poll export status until completed or failed.
            """
            url = f"{self.api_base_url}/odata/Exports({export_id})"
            headers = self._get_headers()

            start_time = time.time()

            while True:
                if time.time() - start_time > max_wait_seconds:
                    raise TimeoutError(
                        f"Export {export_id} did not complete within {max_wait_seconds} seconds"
                    )

                response = requests.get(url, headers=headers)

                if response.status_code != 200:
                    raise RuntimeError(
                        f"Failed to poll export status: {response.status_code} {response.text}"
                    )

                export_status = response.json()
                status = export_status.get("Status")

                if status == "Completed":
                    return
                elif status == "Failed":
                    raise RuntimeError(f"Export {export_id} failed")
                elif status in ["New", "InProgress"]:
                    time.sleep(poll_interval)
                else:
                    raise RuntimeError(f"Unknown export status: {status}")

        def _get_download_link(self, export_id: int) -> str:
            """
            Step 3: Get download link for the completed export.
            """
            url = f"{self.api_base_url}/odata/Exports({export_id})/UiPath.Server.Configuration.OData.GetDownloadLink"
            headers = self._get_headers()

            response = requests.get(url, headers=headers)

            if response.status_code != 200:
                raise RuntimeError(
                    f"Failed to get download link: {response.status_code} {response.text}"
                )

            download_data = response.json()
            download_uri = download_data.get("Uri")

            if not download_uri:
                raise RuntimeError(f"Download link response missing 'Uri': {download_data}")

            return download_uri

        def _download_csv(self, download_url: str) -> str:
            """
            Download and extract CSV file from the signed URL.
            UiPath may return either a plain CSV or a ZIP file containing the CSV.
            """
            # No authentication required for signed URLs
            response = requests.get(download_url)

            if response.status_code != 200:
                raise RuntimeError(
                    f"Failed to download CSV: {response.status_code} {response.text}"
                )

            content = response.content

            # Check if the content is a ZIP file (starts with 'PK')
            if content.startswith(b'PK'):
                # Extract CSV from ZIP
                try:
                    with zipfile.ZipFile(io.BytesIO(content)) as zip_file:
                        # Get the first CSV file in the archive
                        csv_files = [name for name in zip_file.namelist() if name.endswith('.csv')]
                        if not csv_files:
                            raise RuntimeError("No CSV file found in the ZIP archive")

                        # Read the first CSV file
                        with zip_file.open(csv_files[0]) as csv_file:
                            return csv_file.read().decode('utf-8')
                except zipfile.BadZipFile as e:
                    raise RuntimeError(f"Failed to extract ZIP file: {e}")
            else:
                # Plain CSV text
                return response.text

        def _parse_csv(self, csv_content: str) -> Iterator[dict]:
            """
            Parse CSV content and yield records as dictionaries.
            Handles UiPath's actual CSV column names and nested JSON fields.

            UiPath CSV columns:
            - Status, Reference, Priority, Id (match our expected names)
            - "Specific Data" -> SpecificContent
            - "Created (absolute)" -> CreationTime
            - "Deadline (absolute)" -> DueDate
            - "Postpone (absolute)" -> DeferDate
            - "Started (absolute)" -> StartProcessing
            - "Ended (absolute)" -> EndProcessing
            - "Retry No." -> RetryNumber
            - "Transaction Execution Time" -> SecondsInPreviousAttempts
            - Robot, Output, Progress (similar names)
            """
            # Use StringIO with proper newline handling for CSV with multiline fields
            csv_file = io.StringIO(csv_content, newline='')
            csv_reader = csv.DictReader(csv_file)

            for row in csv_reader:
                record = {}

                # Parse basic fields (direct matches)
                record["Id"] = self._parse_int(row.get("Id"))
                record["Priority"] = row.get("Priority")
                record["Status"] = row.get("Status")
                record["Reference"] = row.get("Reference")
                record["Progress"] = row.get("Progress")

                # Fields not in UiPath export - set to reasonable defaults
                record["QueueDefinitionId"] = None  # Not in export CSV
                record["Name"] = None  # Queue name not in export CSV
                record["ReviewStatus"] = None  # Not in export CSV
                record["OrganizationUnitId"] = None  # Not in export CSV
                record["RiskSlaDate"] = None  # Not in export CSV

                # Map UiPath column names to our field names
                record["ProcessingException"] = row.get("Exception") or row.get("Exception Details")
                record["DueDate"] = row.get("Deadline (absolute)")
                record["DeferDate"] = row.get("Postpone (absolute)")
                record["StartProcessing"] = row.get("Started (absolute)")
                record["EndProcessing"] = row.get("Ended (absolute)")
                record["CreationTime"] = row.get("Created (absolute)")

                # Use CreationTime as LastModificationTime if not available
                record["LastModificationTime"] = row.get("LastModificationTime") or row.get("Created (absolute)")

                # Parse integer fields
                record["SecondsInPreviousAttempts"] = self._parse_int(
                    row.get("Transaction Execution Time")
                )
                record["AncestorId"] = self._parse_int(row.get("AncestorId"))
                record["RetryNumber"] = self._parse_int(row.get("Retry No."))

                # Parse JSON fields - UiPath uses "Specific Data" instead of "SpecificContent"
                record["SpecificContent"] = row.get("Specific Data")
                record["Output"] = row.get("Output")

                # Parse nested Robot struct (column name is just "Robot")
                robot_value = row.get("Robot")
                if robot_value and robot_value.strip():
                    record["Robot"] = {"Name": robot_value}
                else:
                    record["Robot"] = None

                # Parse nested ReviewerUser struct (column name is "Reviewer Name")
                reviewer_value = row.get("Reviewer Name")
                if reviewer_value and reviewer_value.strip():
                    record["ReviewerUser"] = {"Username": reviewer_value}
                else:
                    record["ReviewerUser"] = None

                yield record

        def _parse_int(self, value: str) -> int:
            """Parse integer value, return None if empty or invalid."""
            if not value or value == "":
                return None
            try:
                return int(value)
            except (ValueError, TypeError):
                return None

        def _parse_robot(self, row: dict) -> dict:
            """
            Parse Robot nested structure from CSV row.
            CSV may have Robot.Id, Robot.Name, Robot.Type columns.
            """
            robot_id = row.get("Robot.Id") or row.get("RobotId")
            robot_name = row.get("Robot.Name") or row.get("RobotName")
            robot_type = row.get("Robot.Type") or row.get("RobotType")

            if not robot_id and not robot_name:
                return None

            robot = {}
            if robot_id:
                robot["Id"] = self._parse_int(robot_id)
            if robot_name:
                robot["Name"] = robot_name
            if robot_type:
                robot["Type"] = robot_type

            return robot if robot else None

        def _parse_reviewer_user(self, row: dict) -> dict:
            """
            Parse ReviewerUser nested structure from CSV row.
            CSV may have ReviewerUser.Id, ReviewerUser.Username, ReviewerUser.Email columns.
            """
            user_id = row.get("ReviewerUser.Id") or row.get("ReviewerUserId")
            username = row.get("ReviewerUser.Username") or row.get("ReviewerUsername")
            email = row.get("ReviewerUser.Email") or row.get("ReviewerEmail")

            if not user_id and not username:
                return None

            user = {}
            if user_id:
                user["Id"] = self._parse_int(user_id)
            if username:
                user["Username"] = username
            if email:
                user["Email"] = email

            return user if user else None


    ########################################################
    # pipeline/lakeflow_python_source.py
    ########################################################

    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            records, offset = self.lakeflow_connect.read_table(
                self.options[TABLE_NAME], start, self.options
            )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        def __init__(self, options):
            self.options = options
            self.lakeflow_connect = LakeflowConnect(options)

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                # Assuming the LakeflowConnect interface uses get_table_schema, not get_table_details
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)  # pylint: disable=undefined-variable
